#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para Controlador : usuario#
user:
   path: /user
   controller: App\Controller\UserController::index
   methods: [GET]

register:
   path: /register
   controller: App\Controller\UserController::register
   methods: [POST]

login:
   path: /login
   controller: App\Controller\UserController::login
   methods: [POST]

user-edit:
   path: /user/edit
   controller: App\Controller\UserController::edit
   methods: [PUT]


# Rutas para Controlador : usuarVideoio#
video:
   path: /video
   controller: App\Controller\VideoController::index
